# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d70d5cb5-9d17-4c0f-9745-0a7d92de8615";
      fsType = "ext4";
      options = [ "defaults" "noatime" "discard" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7B51-5700";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b78be446-8645-4947-bb6e-49943a979d92";
      fsType = "ext4";
      options = [ "defaults" "noatime" "discard" ];
    };

  fileSystems."/mnt/magnetic" =
    { device = "/dev/mapper/vga-lva";
      fsType = "ext4";
      options = [ "defaults" "noatime" "nodiratime" ];
    };

  fileSystems."/mnt/ssd" =
    { device = "/dev/disk/by-uuid/a9298542-4f8f-49a8-8489-a4fe21fa98b1";
      fsType = "btrfs";
      options = [ "defaults" "noatime" "discard=async" "compress=zstd:3" "space_cache=v2" "ssd" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
